export TYPST_PACKAGE_PATH_CONDA_BACKUP="${TYPST_PACKAGE_PATH:-}"
export TYPST_PACKAGE_PATH="$CONDA_PREFIX/Library/share/typst/packages"

export TYPST_FONT_PATHS_CONDA_BACKUP="${TYPST_FONT_PATHS:-}"
export TYPST_FONT_PATHS="$CONDA_PREFIX/fonts"
