@echo off
set "TYPST_PACKAGE_PATH=%TYPST_PACKAGE_PATH_CONDA_BACKUP%"
set "TYPST_PACKAGE_PATH_CONDA_BACKUP="

set "TYPST_FONT_PATHS=%TYPST_FONT_PATHS_CONDA_BACKUP%"
set "TYPST_FONT_PATHS_CONDA_BACKUP="
