if [ "${TYPST_PACKAGE_PATH_CONDA_BACKUP+x}" ] ; then
  export TYPST_PACKAGE_PATH="$TYPST_PACKAGE_PATH_CONDA_BACKUP"
  unset TYPST_PACKAGE_PATH_CONDA_BACKUP
fi

if [ "${TYPST_FONT_PATHS_CONDA_BACKUP+x}" ] ; then
  export TYPST_FONT_PATHS="$TYPST_FONT_PATHS_CONDA_BACKUP"
  unset TYPST_FONT_PATHS_CONDA_BACKUP
fi
