{% set name = "typst" %}
{% set version = "23-03-28" %}

package:
  name: {{ name | lower }}
  version: {{ version }}

source:
  url: https://github.com/{{ name }}/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 494b0438940a21370d31d44e090e1a6b1b3acabc8b9c4c181455f86441d5cab7

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('rust') }}
    - cargo-bundle-licenses

test:
  commands:
    - typst --version

about:
  home: https://github.com/typst/typst
  license: Apache-2.0
  license_family: Apache
  license_file:
    - LICENSE
    - NOTICE
    - THIRDPARTY_LICENSES.yaml
  summary: A new markup-based typesetting system that is powerful and easy to learn.

extra:
  recipe-maintainers:
    - pavelzw
