{% set name = "typst" %}
{% set version = "0.10.0" %}

package:
  name: {{ name | lower }}
  version: {{ version }}

source:
  url: https://github.com/{{ name }}/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: f1b7baba3c6f6f37dee6d05c9ab53d2ba5cd879a57b6e726dedf9bc51811e132

build:
  number: 2

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('rust') }}
    - cargo-bundle-licenses

test:
  commands:
    - typst --version

about:
  home: https://github.com/typst/typst
  license: Apache-2.0
  license_family: Apache
  license_file:
    - LICENSE
    - NOTICE
    - THIRDPARTY_LICENSES.yaml
  summary: A new markup-based typesetting system that is powerful and easy to learn.

extra:
  recipe-maintainers:
    - freundTech
    - pavelzw
