{% set name = "typst" %}
{% set version = "0.11.0rc1" %}

package:
  name: {{ name | lower }}
  version: {{ version }}

source:
  url: https://github.com/{{ name }}/{{ name }}/archive/refs/tags/v{{ version.replace("rc", "-rc") }}.tar.gz
  sha256: 355697d660054b524f18433658a94bdc75b8684e60f76bc67c3da5bd4d7ce981

build:
  number: 1

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('rust') }}
    - cargo-bundle-licenses
  host:
    - openssl  # [linux]

test:
  commands:
    - typst --version

about:
  home: https://github.com/typst/typst
  license: Apache-2.0
  license_family: Apache
  license_file:
    - LICENSE
    - NOTICE
    - THIRDPARTY_LICENSES.yaml
  summary: A new markup-based typesetting system that is powerful and easy to learn.

extra:
  recipe-maintainers:
    - freundTech
    - pavelzw
